
-- Create the Category table
CREATE TABLE Category (
    CategoryID INT PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL,
    Description VARCHAR(100)
);

-- Insert data into Category table
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (1, 'FOOD SUPPLEMENTS', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (2, 'HERBAL COFFEE MIX', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (3, 'MEDICAL SUPPLY / DEVICE', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (4, 'MEDICINE', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (5, 'MEDINE', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (6, 'PILLS', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (7, 'SOLUTION FOR INJECTION', NULL);
INSERT INTO Category (CategoryID, CategoryName, Description) VALUES (8, 'SUPPLY', NULL);

-- Create the Items table
CREATE TABLE Items (
    ItemID INT PRIMARY KEY,
    ItemName VARCHAR(50) NOT NULL,
    CategoryID INT,
    Price DECIMAL(10, 2) NOT NULL,
    Description VARCHAR(100),
    FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
);

-- Insert data into Items table
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1056, 'BIOMIN VITAMIN PLUS CAPSULE', 1, 7.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1380, 'PAU DE ARCO CAPSULE', 1, 15.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1382, 'MX3 CAPSULE', 1, 18.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1112, 'TIKI-TIKI STAR SYRUP', 1, 126.0, '120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1388, 'M.R 10', 1, 350.0, '500 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1120, 'TIKI-TIKI STAR SYRUP', 1, 70.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1119, 'CEELIN PLUS', 1, 158.5, '30 ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1384, 'TORO CAPSULE', 1, 110.0, '2 CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1118, 'CEELIN PLUS', 1, 99.0, '15 ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1383, 'POWERCELL CAPSULE', 1, 18.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1379, 'XANTHONE PLUS CAPSULE', 1, 18.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1400, 'CHERIFER + ZINC', 1, 204.0, '120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1396, 'CHERIFER FORTE SYRUP', 1, 382.0, '240 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1398, 'CHERIFER FORTE SYRUP', 1, 233.0, '120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1394, 'CHERIFER PGM CAPSULE', 1, 22.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1392, 'MEMO PLUS CAPSULE', 1, 16.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1395, 'NUTRILIN SYRUP', 1, 197.0, '120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1397, 'PROPAN TLC', 1, 118.0, '60 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1399, 'PROPAN TLC', 1, 203.0, '120 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1381, 'KIDNEY CARE CAPSULE', 1, 18.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1385, 'DRIVEMAX CAPSULE', 1, 108.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1131, 'MARKCAFE 5 IN 1 PLUS ONE', 2, 19.0, '21 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1130, 'BESTCAFFE 8 IN 1 COFFEE WITH HERBAL MIX', 2, 14.0, '14 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1132, 'RELAX HERBAL 20 IN 1 COFFEE MIX', 2, 19.0, '18 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1367, 'DISP. SYRINGE WITH NEEDLE', 3, 12.0, '10 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1364, 'DISP. SYRINGE WITH NEEDLE', 3, 7.0, '1 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1362, 'DISP. SYRINGE WITH NEEDLE', 3, 8.0, '5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1361, 'DISP. SYRINGE WITH NEEDLE', 3, 7.0, '3 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1366, 'BT SET', 3, 80.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1153, 'LONGBONE SKIN TRACTION SPLINT', 3, 1395.0, 'LARGE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1351, 'ARM SLING', 3, 85.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1299, 'URINE BAG', 3, 50.0, '200 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1298, 'NEBULIZER KIT', 3, 50.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1300, 'MICROSET', 3, 48.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1304, 'COLOSTOMY BAG SET ADULT', 3, 375.0, '45 MM');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1305, 'MICROPORE TAPE', 3, 65.0, '1 INCHES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1306, 'MICROPORE TAPE', 3, 45.0, '1/2 INCHES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1100, 'PARA-TULLE', 3, 60.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1301, 'MACROSET', 3, 48.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1307, 'GAUZE PAD', 3, 5.0, '4X4');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1376, 'EYE MO RED', 3, 112.0, '7.5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1374, 'BIODERM OITNMENT', 3, 25.0, '5 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1377, 'HIVENT PLUS', 3, 37.0, '2.5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1352, 'URINE COLLECTOR BLUE', 3, 20.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1356, 'SURGICAL BLADE', 3, 15.0, 'G-20');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1355, 'SURGICAL BLADE', 3, 15.0, 'G-11');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1353, 'STERILE STOOL COLLECTOR', 3, 25.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1349, 'STERILE LATEX SURGICAL GLOVES', 3, 28.0, 'SIZE 7.0');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1378, 'RELAXSAPH NEBULE', 3, 37.0, '500 MCG + 2.5 ML NEBULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1359, 'PRIMEPAD WADDING SHEET', 3, 90.0, '4X5 INCHES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1390, 'PREGANCY TEST KIT', 3, 55.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1368, 'PEDIA URINE COLLECTOR', 3, 15.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1375, 'NIZORAL CREAM', 3, 155.0, '3.5 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1369, 'NASAL OXYGEN CANNULA', 3, 50.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1373, 'SILLVER SULFADIAZINE OINTMENT', 3, 175.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1365, 'LONGBONE PLASTER OF PARIS', 3, 145.0, '6X5 YARDS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1213, 'SINOCARE GLUCOMETER', 3, 569.0, '1 UNIT');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1372, 'HYCLENS GARGLE', 3, 285.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1354, 'MEDICINE CUP', 3, 5.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1371, 'HYDROGEN PEROXIDE', 3, 35.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1363, 'INSYTE-W', 3, 50.0, 'G-24');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1124, 'ABDOMINAL BINDER BLUE', 3, 220.0, '8 X 49 INCHES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1357, 'IV CANNNULA', 3, 30.0, 'G-22');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1389, 'LANCET', 3, 5.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1350, 'LATEX SURGICAL GLOVES', 3, 30.0, 'SIZE 8');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1358, 'IV CANNNULA', 3, 30.0, 'G-26');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1198, 'VONWELT COLCHICINE', 4, 8.0, '500 MCG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1175, 'SKELAN 550', 4, 22.0, '550 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1102, 'SOLMUX', 4, 123.0, '100 MG/5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1162, 'VONWELT HYOSCINE', 4, 9.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1103, 'SOLMUX', 4, 132.0, '200 MG / 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1214, 'SOLVOMOX', 4, 17.0, '2 MG/100 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1086, 'SYMDEX-D', 4, 60.0, '6.25 MG / 500 MCG / 125 MG PER ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1087, 'SYMDEX-D', 4, 45.0, '6.25 MG / 500 MCG / 100 MG PER ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1178, 'TRIFOCID', 4, 6.0, '50 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1201, 'TELSITAN-80', 4, 19.0, '80 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1096, 'TEMPRA FORTE', 4, 160.0, '250 MG/5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1199, 'TERAZIDINE', 4, 22.0, '35 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1195, 'SPIRODEN', 4, 81.0, '25 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1184, 'SYMDEX-D', 4, 5.0, '25 MG / 2 MG / 325 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1035, 'CEFIXIME', 4, 45.0, '200 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1158, 'SENOKOT FORTE', 4, 22.0, '17.54 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1185, 'PROXEN', 4, 10.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1110, 'RAPHC SYRUP', 4, 55.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1167, 'XIBORA-120', 4, 29.0, '120 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1093, 'REAX', 4, 75.0, '2.5 MG / ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1161, 'RE-LEAF FORTE', 4, 14.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1108, 'RILEM MULTILEM SYRUP', 4, 52.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1091, 'RIPHEN', 4, 35.0, '2 MG / 5 ML SYRUP 60ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1085, 'SINUDRIN', 4, 38.0, '6.25 MG/5ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1165, 'SAPHETOR 90', 4, 24.0, '90 MG FILM-COATED TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1220, 'SAPHLOR-100', 4, 12.0, '100 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1218, 'SAPHLOR-50', 4, 6.0, '50 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1216, 'SAPHMIRATE-T50', 4, 18.0, '50 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1194, 'SAPHORBIDE-30', 4, 23.0, '30 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1193, 'SAPHORBIDE-60', 4, 27.0, '60 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1181, 'SAPHROXOL - T30', 4, 6.0, '30 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1204, 'SCHEEPRIN', 4, 4.0, '80 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1164, 'SAPHLECOX 200', 4, 18.0, '200 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1171, 'ZENTEK', 4, 23.0, '150 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1281, 'QUADMAX', 4, 14.0, '150 MG / 75 MG / 400 MG + 275 MG');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1277, 'ALLECUR', 4, 4.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1276, 'LARADIN', 4, 12.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1283, 'MEBENDAZOLE', 4, 9.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1257, 'MEPTIN', 4, 22.0, '50 MCG');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1275, 'PRED 10', 4, 8.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1274, 'PRED 20', 4, 12.0, '20 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1265, 'PREDNISONE', 4, 8.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1163, 'PRELAX', 4, 8.0, '5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1262, 'SPASMOMEN', 4, 25.5, '40 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1271, 'SYSTOCOR', 4, 5.0, '5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1251, 'TRANEXT', 4, 19.0, '500 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1255, 'VENTREX', 4, 4.0, '2 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1284, 'XYCLOVIRAX', 4, 25.0, '200 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1285, 'XYCLOVIRAX FORTE', 4, 32.0, '800 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1293, 'BIOGESIC', 4, 5.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1302, 'ELECTAB', 4, 15.0, '600 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1391, 'FERLIN', 4, 357.0, '120 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1393, 'AMECIRON', 4, 7.0, 'TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1291, 'KATHREX', 4, 12.0, '960 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1254, 'ALBULEM', 4, 4.0, '2 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1263, 'ISOXILAN', 4, 28.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1250, 'HEMOSTAN', 4, 46.0, '500 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1253, 'AUROHEX', 4, 23.0, '5 MG CHEWABLE TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1261, 'BONAMINE', 4, 16.0, '12.5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1264, 'BONAMINE', 4, 22.0, '25 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1288, 'BRITAMOX', 4, 9.0, '500 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1256, 'BUTAMOL', 4, 6.0, '4 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1287, 'CLOXANE', 4, 22.0, '500 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1290, 'CO-AMOXICLAV', 4, 40.0, '625 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1266, 'CORT', 4, 12.0, '20 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1292, 'CYFROX', 4, 22.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1259, 'DAFLON 500', 4, 54.0, '450 MG / 50 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1273, 'DECILONE FORTE', 4, 37.0, '4 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1258, 'DRAMELIN', 4, 6.0, '50 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1272, 'DRENEX', 4, 29.0, '3 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1260, 'DUPHASTON', 4, 98.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1286, 'EXEL', 4, 9.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1280, 'FLAGEX', 4, 6.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1279, 'FLAGYL FORTE', 4, 10.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1278, 'IMPODEX', 4, 10.0, '500 MCG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1192, 'PREGAMED - 75', 4, 45.0, '75 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1203, 'TORVASTATIN', 4, 22.0, '20 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1156, 'PIDCLIN', 4, 6.0, '100 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1219, 'AMLODIPINE', 4, 6.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1182, 'ARCOXIA', 4, 62.75, '90 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1186, 'ASCOF FORTE', 4, 8.0, '600 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1190, 'ASFLEM', 4, 6.0, '300 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1105, 'ASMALIN', 4, 138.0, '2 MG / 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1202, 'ATORSAPH-20', 4, 22.0, '20 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1097, 'BIOGESIC', 4, 76.25, '100 MG / ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1088, 'BROMUX', 4, 32.0, '6 MG/ML 15 ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1070, 'CALCIE', 4, 7.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1206, 'CAPTOBES', 4, 7.0, '25 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1208, 'CARVIDA 6.25', 4, 12.0, '6.25 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1115, 'CEELIN AGES 0-2', 4, 80.0, '100 MG / ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1114, 'CEELIN AGES 2-12', 4, 69.5, '100 MG / 5 ML SYRUP 60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1211, 'CITISAPH-500', 4, 55.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1207, 'CLODIN', 4, 24.0, '75 MCG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1082, 'COLDS-OFF', 4, 49.0, '12.5 MG/5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1210, 'COPIDE', 4, 24.0, '75 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1076, 'CORTAL 500', 4, 10.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1159, 'DATAB', 4, 5.0, '2 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1075, 'DECOLGEN FORTE', 4, 8.0, '25 MG / 2 MG/ 500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1092, 'DIACIEL', 4, 45.0, '10 MG / 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1217, 'DIADIPINE', 4, 5.0, '5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1157, 'DICYRINE', 4, 7.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1099, 'DISUDRIN', 4, 145.0, '5 MG / 1 MG 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1098, 'DISUDRIN', 4, 136.0, '2.5 MG / 500 MCG DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1117, 'DM FERROUS SULFATE', 4, 75.0, '220 MG / 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1090, 'DM MEBENDAZOLE', 4, 65.0, '100MG / 5 ML SUSPENSION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1183, 'DOLFENAL', 4, 34.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1174, 'DOLFENAL', 4, 18.0, '250 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1078, 'ALVEDON', 4, 7.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1170, 'DUO-GESIC', 4, 20.0, '325 MG / 37.5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1172, 'ALUMINOX', 4, 3.0, '300 MG / 200 MG CHEWABLE TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1215, 'A.R.A + H', 4, 12.0, '50 MG / 12.5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1032, 'CEFUROX', 4, 260.0, '125MG/5ML SUSPENSION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1036, 'CLARITHROMYCIN', 4, 48.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1034, 'DM CLARITHROMYCIN', 4, 275.0, '125MG / 5ML 50ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1037, 'ERYTHROMYCIN', 4, 10.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1033, 'SQCEF', 4, 350.0, '250MG/5ML 50ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1039, 'BUSCOPAN PLUS', 4, 40.75, '10 MG / 500 MG');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1045, 'DOLO NEUROBION', 4, 31.0, '500MG/50MG/100MG/100MCG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1043, 'EURIVIT  - M TABLET', 4, 7.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1042, 'FOLART', 4, 10.0, '5 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1044, 'HEMARATE FA TABLET', 4, 26.25, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1038, 'KREMIL - S ADVANCE', 4, 22.0, '10 MG/800 MG / 165 MG CHEWABLE TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1040, 'LOMOTIL', 4, 12.0, '2MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1041, 'SINECOD FORTE', 4, 25.0, '50 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1058, 'Unknown', 4, 9.0, '20 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1053, 'ALAXAN', 4, 9.0, '200 MG / 325 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1054, 'ALAXAN FR', 4, 9.0, '200 MG / 325 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1067, 'APPEBON WITH IRON', 4, 20.0, 'CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1069, 'ASCORBIC ACID', 4, 7.0, '500 MG TABLET SUGAR-FREE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1068, 'CALCIUMADE TABLET', 4, 11.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1066, 'CALTRATE ADVANCE', 4, 12.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1061, 'CENTRUM ADVANCE', 4, 12.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1063, 'CENTRUM SILVER ADVANCE', 4, 13.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1065, 'FERUZ', 4, 3.0, '104.84 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1055, 'MEDICOL ADVANCE 400', 4, 14.0, '400 MG SOFTGEL CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1062, 'MYRA E', 4, 14.0, '400 I.U CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1064, 'MYREVIT - B', 4, 3.0, '100 MG/10 MG/50 MCG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1059, 'REXILAN', 4, 12.0, '450 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1060, 'TAPDIN', 4, 28.0, '5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1083, '4NAZAL', 4, 49.0, '12.5 MG / 5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1089, 'ACIFLAM', 4, 55.0, '50 MG / 5 ML SUSPENSION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1109, 'EURIVIT SYRUP', 4, 35.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1423, 'IBUFEN', 4, 12.0, '400 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1205, 'GOTORVAST 40', 4, 32.0, '40 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1169, 'OMEPHIL-20', 4, 23.0, '20 MG BP CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1071, 'OSCIVIT', 4, 15.0, '1250 MG /250 IU TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1095, 'PENFRO', 4, 85.0, '200 MG/5 ML SUSPENSION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1111, 'NOVACEE', 4, 85.0, '100 MG / 5 ML SYRUP 120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1081, 'PHENAMINE', 4, 49.0, '12.5 MG/5ML SYRUP 60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1212, 'METOCARD', 4, 7.0, '100 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1101, 'NEOZEP', 4, 115.0, '1 MG / 0.8 MG DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1196, 'FUSEDEX', 4, 10.0, '40 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1079, 'NEOZEP', 4, 7.0, '10 MG / 2 MG / 500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1074, 'NAFARIN - A', 4, 9.0, '125 MG / 20 MG / 1 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1072, 'FORALIVIT CAPSULE', 4, 7.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1191, 'FLUIMUCIL', 4, 25.0, '200 MG GRANULES FOR SOLUTION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1173, 'FLANAX FORTE', 4, 24.0, '550 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1209, 'FINASTERIDE', 4, 15.0, '5 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1189, 'OFPLEMED', 4, 6.0, '300 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1084, 'MYREX PHENYLPROPANOLAMINE', 4, 49.0, '12.5 MG / 5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1168, 'INHIBITA', 4, 27.0, '40 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1197, 'MICOR', 4, 15.0, '40 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1080, 'KIDDILETS', 4, 5.0, '120 MG CHEWABLE TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1106, 'KOVENT SF', 4, 450.0, '25 MCG / 250 MCG INHALER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1094, 'MOTILLEX', 4, 45.0, '5 MG / 5 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1188, 'LAGUNGEN', 4, 6.0, '300 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1073, 'MULTICAPS', 4, 7.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1180, 'MARLUXYN', 4, 6.0, '500 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1160, 'LORAGEN', 4, 15.0, '10 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1179, 'MYREMOL', 4, 4.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1104, 'EXPEL', 4, 130.0, '15 MG /5 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1116, 'MYREVIT', 4, 47.0, '15 ML DROPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1113, 'FEROLEM', 4, 55.0, '15 MG / 0.6 ML SYRUP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1107, 'MYREVIT SYRUP', 4, 52.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1176, 'MYREFEN', 4, 5.0, '250 MG CAPSULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1177, 'GOPAIN', 4, 6.0, '500 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1294, 'BIOFLU', 5, 9.0, 'TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1252, 'CINZITAB', 5, 9.0, '25 MG TABLET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1387, 'ALTHEA PILLS', 6, 515.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1386, 'LADY PILLS', 6, 55.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1326, 'NAUSIL', 7, 85.0, '5 MG/5ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1417, 'ABHAYRAB', 7, 950.0, 'VIAL WITH SYRINGE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1320, 'LYCORTIS', 7, 250.0, '100 MG POWDER FOR INJECTION VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1311, 'KLORFEN', 7, 128.0, '1 G VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1318, 'KETOPANE', 7, 65.0, '30 MG/ML AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1052, 'EPIBBAS', 7, 90.0, '1MG/ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1328, 'ZANTRICID', 7, 136.0, '25 MG/ML (50MG/2ML)');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1316, 'XYLODENT', 7, 55.0, '20 MG / 10 MCG PER ML (36 MG/18 MCG PER 1.8 ML)');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1317, 'ELCILIN', 7, 125.0, '500 MG POWDER FOR INJ.');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1315, 'CORPILYN', 7, 185.0, '1 G POWDER VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1050, 'EPICARE', 7, 90.0, '1MG/ML AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1319, 'CITISAPH', 7, 195.0, '250 MG/ML (1 G/4 ML) AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1047, 'AMBIVIT K', 7, 85.0, '10 MG/ML AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1048, 'RANITEMP', 7, 385.0, '1G/100ML VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1314, 'STERILE WATER FOR INJECTION', 7, 50.0, '20 ML VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1313, 'STERILE WATER FOR INJECTION', 7, 75.0, '50 ML VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1309, 'AMBIDOL', 7, 135.0, '50 MG / ML (100 MG / 2 ML)');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1308, 'AMADOL', 7, 95.0, '150 MG / ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1310, 'SAPHSODEX', 7, 122.0, '4 MG / 2 ML ( 8 MG / 2 ML)');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1051, 'HYOSAPH', 7, 55.0, '20MG/ML AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1046, 'LIDOPHIL', 7, 250.0, '20 MG/ML (2% W/V) 50 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1049, 'LORECARE', 7, 105.0, '10MG/ML AMPOULE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1312, 'PHIZOLIN', 7, 125.0, '1 G VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1327, 'ROSEMIDE', 7, 80.0, '10 MG/ML (20 MG/2 ML)');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1329, 'MAGNESIUM SULFATE', 7, 75.0, '250 MG/ML (25%) 20 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1322, 'MEDIPRAZOLE IV', 7, 180.0, '40 MG POWDER FOR INJECTION VIAL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1187, 'KATINKO OINTMENT', 8, 38.0, '10 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1143, 'SILKA SOAP', 8, 28.0, '65 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1343, 'MODESS ALL NIGHT / EXTRA LONG', 8, 157.0, '10 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1370, 'LAMPIEN XXL', 8, 50.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1222, 'LAMPIEN NEWBORN', 8, 99.0, '15 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1146, 'LS BL SOAP', 8, 48.0, '115 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1346, 'SISTERS PANTYLINERS', 8, 33.0, '20+2 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1344, 'MODESS ULTRA THIN', 8, 178.0, '10 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1422, 'JADE HANDY PACK', 8, 14.0, '40 PULL UP');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1420, 'GREEN CROSS SOAP', 8, 25.0, '60G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1419, 'DEOPLUS TAWAS POWDER', 8, 24.0, '50G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1413, 'TENDER LOVE WIPES', 8, 35.0, '20 SHEET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1410, 'TENDER LOVE WIPES', 8, 65.0, '100');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1406, 'TENDER CARE POWDER', 8, 33.0, '50 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1404, 'SWEETBABY DIAPER', 8, 10.0, 'LARGE');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1405, 'SWEETBABY DIAPER', 8, 14.0, 'XL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1402, 'SMART CHOICE TISSUE', 8, 20.0, '2 PER PACK');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1414, 'MAMA COTTON BUDS', 8, 13.0, '50 TIPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1403, 'LAMPIEN NEWBORN', 8, 95.0, '12 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1348, 'MODESS NON-WINGS', 8, 8.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1416, 'GREEN CROSS ISOPROPHYL ALCOHOL 40% WITH MOISTURIZER', 8, 39.0, '150 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1412, 'GRAND ADULT DIAPER MEDIUM', 8, 28.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1408, 'CASINO REGULAR', 8, 39.0, '150 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1407, 'CASINO ETHYL ALCOHOL', 8, 29.0, '70% 60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1415, 'CASINO ETHYL ALCOHOL', 8, 29.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1401, 'SUMMIT', 8, 17.0, '500 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1127, 'PURITY COTTON BALLS', 8, 23.0, '30 BALLS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1148, 'REXONA MEN & WOMEN', 8, 12.0, '3 ML SACHET');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1138, 'ROYAL NIPPLE LARGE HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1137, 'ROYAL NIPPLE MEDIUM HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1136, 'ROYAL NIPPLE SMALL HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1128, 'SANICARE COTTON BALLS', 8, 49.0, '150 BALLS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1409, 'GREEN CROSS ALCOHOL WITH MOISTURIZER 70%', 8, 44.0, '150 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1122, 'KAMI INTERFOLEDED PAPER TOWEL', 8, 60.0, '17 PULLS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1341, 'THOSEDAYS WINGS', 8, 24.0, '8 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1123, 'KAMI ALL PURPOSE PAPER TOWEL', 8, 60.0, '120 PULLS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1125, 'HAPPY COTTON', 8, 10.0, '10 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1121, 'TISSUE ROLL', 8, 15.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1421, 'TENDER CARE POWDER', 8, 63.0, '100 GRAM');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1154, 'GRAND ADULT DIAPER LARGE', 8, 30.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1200, 'TRUST CONDOM ASSORTED', 8, 32.0, '3''S');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1233, 'WIPE COTTON', 8, 26.0, '40 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1140, 'COLGATE TOOTHPASTE', 8, 14.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1268, 'NATURES SPRING', 8, 25.0, '1 LITER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1270, 'NATURES SPRING', 8, 85.0, '6.6 LITER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1267, 'NATURES SPRING', 8, 20.0, '500 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1269, 'NATURES SPRING', 8, 70.0, '5 LITER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1232, 'WIPE COTTON', 8, 10.0, '10 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1145, 'GILLETTE SHAVER YELLOW', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1239, 'LAMPIEN XL', 8, 46.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1126, 'HAPPY COTTON', 8, 26.0, '40 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1240, 'LAMPIEN MEDIUM', 8, 36.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1243, 'HAPPY DIAPER XL', 8, 40.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1246, 'HAPPY DIAPER MEDIUM', 8, 32.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1244, 'HAPPY DIAPER LARGE', 8, 35.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1241, 'FRESH TOOTHBRUSH', 8, 17.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1221, 'EXTRA COTTONBUDS', 8, 18.0, '108 TIPS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1247, 'CARE ADULT DIAPER LARGE', 8, 30.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1248, 'CARE ADULT DIAPER MEDIUM', 8, 28.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1242, 'CARESS UNDERPAD XL', 8, 35.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1141, 'DR. S. WONG SULFUR SOAP', 8, 45.0, '80 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1235, 'CASINO ALCOHOL ACTIVE', 8, 40.0, '150 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1228, 'EQ COLOR LARGE', 8, 38.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1229, 'EQ COLOR MEDIUM', 8, 34.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1227, 'EQ COLOR SMALL', 8, 32.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1236, 'CASINO ALCOHOL ACTIVE', 8, 56.0, '250 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1238, 'LAMPIEN LARGE', 8, 40.0, '4 DIAPER');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1338, 'ACEITE DE ALCAMFORADO', 8, 28.0, '50 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1339, 'ACEITE DE ALCAMFORADO', 8, 20.0, '25 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1325, 'AROMATIC SPIRIT OF AMMONIA', 8, 55.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1231, 'TENDER CARE POWDER', 8, 22.0, '25 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1347, 'CHARMEE PANYTLINERS', 8, 26.0, '20+2 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1345, 'CAREFREE SUPER DRY', 8, 37.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1230, 'TENDER LOVE WIPES', 8, 35.0, '20 SHEETS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1144, 'ASSORTED BIODERM SOAP', 8, 35.0, '60 G');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1142, 'ASSORTED SAFEGUARD SOAP', 8, 25.0, '60 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1297, 'VICKS VAPORUB', 8, 39.0, '5 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1296, 'VICKS VAPORUB', 8, 69.0, '10 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1139, 'ASSORTED SHAMPOO', 8, 8.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1234, 'CASINO ALCOHOL ACTIVE', 8, 29.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1335, 'SALICYLIC ACID', 8, 25.0, '50 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1334, 'SALICYLIC ACID', 8, 20.0, '25 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1332, 'REGULAR EFFICASCENT OIL', 8, 98.25, '100 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1330, 'OMEGA PAIN KILLER', 8, 84.0, '60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1333, 'OMEGA ADVANCE SPRAY', 8, 95.0, '50 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1337, 'OMEGA  LINIMENT', 8, 70.0, '30 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1340, 'OMEGA  LINIMENT', 8, 136.0, '120 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1224, 'THOSEDAYS NON-WINGS', 8, 22.0, '8 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1321, 'CALAMINE LOTION', 8, 105.0, '8% LOTION 60 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1147, 'PONDS CLEAR SOLUTIONS', 8, 17.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1226, 'BEYBIKO BABY WIPES', 8, 65.0, '80 + 20 SHEETS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1223, 'BEYBIKO BABY WIPES', 8, 35.0, '20 SHEETS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1324, 'EUGENOL', 8, 35.0, '1.25 MG/ML SOLUTION');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1150, 'APOLLO PETROLEUM JELLY', 8, 46.0, '25 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1331, 'EXTRA STRENGTH EFFICASCENT OIL', 8, 127.0, '100 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1135, 'BABYFLO NIPPLE SMALL HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1336, 'METHYL SALICYCLATE', 8, 50.0, '50 ML');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1134, 'BABYFLO NIPPLE MEDIUM HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1133, 'BABYFLO NIPPLE LARGE HOLE', 8, 27.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1129, 'HAPPY COTTON BALLS', 8, 49.0, '150 BALLS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1149, 'ASSORTED TAWAS POWDER', 8, 24.0, '50 GRAMS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1155, 'BAND-AID', 8, 3.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1342, 'CHARMEE YELLOW', 8, 25.0, '8+1 PADS');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1151, 'ASSORTED STREPSILS', NULL, 72.0, '8 LOZENGES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1152, 'STREPSILS CHESTY COUGH', NULL, 78.0, '6 LOZENGES');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1323, 'EUGENOL', NULL, 0.0, 'NULL');
INSERT INTO Items (ItemID, ItemName, CategoryID, Price, Description) VALUES (1418, 'CARESS UNDERPAD LARGE', NULL, 30.0, 'NULL');

-- Join Items with Category
SELECT 
    Items.ItemID,
    Items.ItemName,
    Items.CategoryID,
    Category.CategoryName,
    Items.Price,
    Items.Description
FROM 
    Items
JOIN 
    Category
ON 
    Items.CategoryID = Category.CategoryID;
